### ISSUE TITLE
Ordinals like first, second, third are not getting converted

### ISSUE THREAD

**Issue by ankurzing** [allo-media/text2num#47]
Ordinals like first, second, third when written alone are not getting converted. How to control when to consider ordinals and when to not?

**Comment by rtxm** [comment]
The three first ordinals are never converted because most of the time it results in bad style. 

Historically `text2num` was first developed to increase legibility of speech transcripts. Now, it is more and more used to pre-process text for machine analysis/learning/NLU or databases, so we plan to add some options to give developers finer control.
